const key='greenEmpirePrototypeV2';
const strains=[
{id:'dream',name:'Green Dream',img:'https://commons.wikimedia.org/wiki/Special:FilePath/Flowering%20cannabis%20plant.jpg',time:90,yield:42,value:6},
{id:'storm',name:'Purple Storm',img:'https://commons.wikimedia.org/wiki/Special:FilePath/Cannabis%20citrus%20super%20haze.jpg',time:120,yield:58,value:8},
{id:'lemon',name:'Lemon Sky',img:'https://commons.wikimedia.org/wiki/Special:FilePath/Cannabis%20flowering.jpg',time:150,yield:72,value:10},
{id:'gold',name:'Northern Gold',img:'https://commons.wikimedia.org/wiki/Special:FilePath/Northern-lights-flowering.jpg',time:180,yield:95,value:13}
];
const defaultState={name:'Rookie',level:1,xp:0,cash:750,gems:30,rep:0,room:1,inventory:{dream:0,storm:0,lemon:0,gold:0},slots:[null,null,null,null],log:['Green Empire gestartet. Dein erster Raum ist bereit.'],upgrades:{rack:0,speed:0,rep:0}};
let s=JSON.parse(localStorage.getItem(key)||'null')||structuredClone(defaultState);
function xpNeed(){return 80+(s.level-1)*60}
function addXp(n){s.xp+=n;while(s.xp>=xpNeed()){s.xp-=xpNeed();s.level++;s.cash+=250;note('Level '+s.level+' erreicht: +250 €','good')}}
function note(msg,cls){s.log.unshift({msg:msg,cls:cls||''});s.log=s.log.slice(0,24)}
function toast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');setTimeout(function(){t.classList.remove('show')},1300)}
function save(){localStorage.setItem(key,JSON.stringify(s));render()}
function totalStock(){return Object.values(s.inventory).reduce(function(a,b){return a+b},0)}
function slotMax(){return Math.min(4,2+s.upgrades.rack)}
function effectiveTime(base){return Math.max(35,Math.round(base*(1-s.upgrades.speed*.15)))}
function startPlant(slot,strainId){if(slot>=slotMax())return toast('Slot noch gesperrt');if(s.slots[slot])return;const st=strains.find(function(x){return x.id===strainId});const cost=Math.round(st.value*6);if(s.cash<cost)return toast('Zu wenig Cash');s.cash-=cost;s.slots[slot]={strainId:strainId,start:Date.now(),duration:effectiveTime(st.time)*1000};note(st.name+' in Slot '+(slot+1)+' gestartet (-'+cost+' €)');save()}
function plantProgress(slot){const p=s.slots[slot];if(!p)return 0;return Math.min(100,((Date.now()-p.start)/p.duration)*100)}
function harvest(slot){const p=s.slots[slot];if(!p||plantProgress(slot)<100)return;const st=strains.find(function(x){return x.id===p.strainId});const amount=Math.round(st.yield*(1+s.room*.05));s.inventory[st.id]+=amount;s.slots[slot]=null;s.rep+=1+s.upgrades.rep;addXp(18);note(amount+' g '+st.name+' geerntet','good');save()}
function plantCard(slot){const p=s.slots[slot],locked=slot>=slotMax();if(locked)return '<div class="plant"><div class="plantImg lockImg">🔒</div><div class="plantBody"><div class="plantTitle"><span>Slot '+(slot+1)+'</span><span class="badge">gesperrt</span></div><button class="btn alt full" disabled>Upgrade nötig</button></div></div>';if(!p){const st=strains[(slot+s.level-1)%strains.length];return '<div class="plant"><div class="plantImg" style="background-image:url(\''+st.img+'\')"></div><div class="plantBody"><div class="plantTitle"><span>'+st.name+'</span><span class="badge">bereit</span></div><div class="tiny">Kosten '+Math.round(st.value*6)+' € · ca. '+effectiveTime(st.time)+' Sek.</div><button class="btn full" onclick="startPlant('+slot+',\''+st.id+'\')">Starten</button></div></div>'}const st=strains.find(function(x){return x.id===p.strainId}),prog=plantProgress(slot),left=Math.max(0,Math.ceil((p.duration-(Date.now()-p.start))/1000));return '<div class="plant"><div class="plantImg" style="background-image:url(\''+st.img+'\')"></div><div class="plantBody"><div class="plantTitle"><span>'+st.name+'</span><span class="badge">'+Math.floor(prog)+'%</span></div><div class="progress"><i style="width:'+prog+'%"></i></div><div class="tiny">'+(prog>=100?'erntereif':'noch '+left+' Sek.')+'</div><button class="btn full" '+(prog<100?'disabled':'')+' onclick="harvest('+slot+')">Ernten</button></div></div>'}
function renderPlants(){const html=[0,1,2,3].map(plantCard).join('');document.getElementById('plantGrid').innerHTML=html;document.getElementById('plantGridFull').innerHTML=html}
function renderInventory(){document.getElementById('inventoryList').innerHTML=strains.map(function(st){return '<div class="row"><div><b>'+st.name+'</b><div class="tiny">Lagerbestand</div></div><b>'+s.inventory[st.id]+' g</b></div>'}).join('')}
function sell(id,amount){const st=strains.find(function(x){return x.id===id});if(s.inventory[id]<amount)return toast('Nicht genug Bestand');const money=Math.round(amount*st.value*(1+s.rep*.002));s.inventory[id]-=amount;s.cash+=money;addXp(8);note(amount+' g '+st.name+' an NPC verkauft: +'+money+' €','good');save()}
function renderSell(){document.getElementById('sellList').innerHTML=strains.map(function(st){return '<div class="row"><div><b>'+st.name+'</b><div class="tiny">Sofortverkauf: 10 g</div></div><button class="btn" onclick="sell(\''+st.id+'\',10)">+'+Math.round(10*st.value*(1+s.rep*.002))+' €</button></div>'}).join('')}
const orderTemplates=[['dream',20,170],['storm',25,260],['lemon',30,390],['gold',35,570]];
function renderOrders(){document.getElementById('ordersList').innerHTML=orderTemplates.map(function(o,i){const st=strains.find(function(x){return x.id===o[0]});return '<div class="order"><div class="orderTop"><b>NPC-Auftrag #'+(i+1)+': '+st.name+'</b><span class="badge">'+o[1]+' g</span></div><div class="tiny">Belohnung '+(o[2]+s.level*12)+' € · +'+(4+i)+' Ruf</div><button class="btn" style="margin-top:8px" onclick="completeOrder(\''+o[0]+'\','+o[1]+','+o[2]+','+(4+i)+')">Liefern</button></div>'}).join('')}
function completeOrder(id,amount,reward,rep){if(s.inventory[id]<amount)return toast('Nicht genug Bestand');s.inventory[id]-=amount;s.cash+=reward+s.level*12;s.rep+=rep;addXp(20);note('Auftrag abgeschlossen: +'+(reward+s.level*12)+' € / +'+rep+' Ruf','good');save()}
function upgrade(type){const costs={rack:900,speed:1200,rep:1500};const levels=s.upgrades[type];const cost=Math.round(costs[type]*Math.pow(1.7,levels));if(s.cash<cost)return toast('Zu wenig Cash');if(type==='rack'&&levels>=2)return toast('Maximal');if(type!=='rack'&&levels>=3)return toast('Maximal');s.cash-=cost;s.upgrades[type]++;if(type==='rack')s.room++;note('Upgrade gekauft: '+type+' Stufe '+s.upgrades[type],'good');save()}
function renderUpgrades(){const data=[['rack','Zusätzlicher Pflanzenslot','Mehr aktive Slots'],['speed','Raumtempo','Kürzere Spieltimer'],['rep','Kontakt-Netzwerk','Mehr Ruf pro Ernte']];document.getElementById('upgradeList').innerHTML=data.map(function(x){const k=x[0],base={rack:900,speed:1200,rep:1500}[k],cost=Math.round(base*Math.pow(1.7,s.upgrades[k]));return '<div class="row"><div><b>'+x[1]+' · Stufe '+s.upgrades[k]+'</b><div class="tiny">'+x[2]+'</div></div><button class="btn goldBtn" onclick="upgrade(\''+k+'\')">'+cost+' €</button></div>'}).join('')}
const rivals=[['Kiosk Crew',3,220],['Dockside Boys',8,540],['Night Owls',15,1100],['City Kings',24,2400]];
function fight(i){const r=rivals[i],power=s.level+s.rep*.15+s.room*2,chance=Math.max(.2,Math.min(.85,.5+(power-r[1])*.035));if(Math.random()<chance){s.cash+=r[2];s.rep+=3+i;addXp(16);note('Rivale '+r[0]+' geschlagen: +'+r[2]+' €','good');toast('Sieg!')}else{const loss=Math.min(s.cash,Math.round(r[2]*.15));s.cash-=loss;note('Gegen '+r[0]+' verloren: -'+loss+' €','bad');toast('Niederlage')}save()}
function renderRivals(){document.getElementById('rivalList').innerHTML=rivals.map(function(r,i){const power=s.level+s.rep*.15+s.room*2,chance=Math.round(Math.max(.2,Math.min(.85,.5+(power-r[1])*.035))*100);return '<div class="row"><div><b>'+r[0]+'</b><div class="tiny">Schwierigkeit '+r[1]+' · ca. '+chance+'% Chance</div></div><button class="btn alt" onclick="fight('+i+')">Duell</button></div>'}).join('')}
function renderRanking(){const score=Math.round(s.level*1200+s.rep*80+s.cash+totalStock()*4),rows=[['GreenWolf',18400],['PurpleKing',15100],['DockBoss',11900],['NeonLeaf',8700],[s.name,score],['Rookie77',4100],['BasementBen',2300]].sort(function(a,b){return b[1]-a[1]});document.getElementById('rankingList').innerHTML=rows.map(function(r,i){return '<div class="rank '+(r[0]===s.name?'me':'')+'"><b>#'+(i+1)+'</b><span>'+r[0]+'</span><b>'+r[1].toLocaleString('de-DE')+'</b></div>'}).join('')}
function testPack(g,c){s.gems+=g;s.cash+=c;note('Test-Premium: +'+g+' 💎 / +'+c+' €','good');save()}
function finishAll(){if(s.gems<25)return toast('Zu wenig Diamanten');s.gems-=25;s.slots=s.slots.map(function(p){return p?Object.assign({},p,{start:Date.now()-p.duration}):p});note('Growth Boost aktiviert (-25 💎)','good');save()}
function vipBoost(){if(s.gems<20)return toast('Zu wenig Diamanten');s.gems-=20;s.rep+=10;s.cash+=500;note('VIP Bonus: +10 Ruf / +500 €','good');save()}
function renderLog(){document.getElementById('logList').innerHTML=(s.log||[]).map(function(x){return typeof x==='string'?'<div>'+x+'</div>':'<div class="'+(x.cls||'')+'">'+x.msg+'</div>'}).join('')}
function render(){document.getElementById('levelStat').textContent=s.level;document.getElementById('cashStat').textContent=Math.round(s.cash).toLocaleString('de-DE')+' €';document.getElementById('stockStat').textContent=totalStock()+' g';document.getElementById('gemsStat').textContent=s.gems+' 💎';document.getElementById('playerNameLabel').textContent=s.name;document.getElementById('nameInput').value=s.name;document.getElementById('repStat').textContent=s.rep;document.getElementById('roomStat').textContent=s.room;renderPlants();renderInventory();renderSell();renderOrders();renderUpgrades();renderRivals();renderRanking();renderLog();localStorage.setItem(key,JSON.stringify(s))}
function activateTab(id){document.querySelectorAll('[data-tab]').forEach(function(b){b.classList.toggle('active',b.dataset.tab===id)});document.querySelectorAll('.tab').forEach(function(t){t.classList.add('hidden')});document.getElementById(id).classList.remove('hidden');window.scrollTo({top:0,behavior:'smooth'})}
document.querySelectorAll('[data-tab]').forEach(function(b){b.addEventListener('click',function(){activateTab(b.dataset.tab)})});
document.getElementById('nameInput').addEventListener('change',function(e){s.name=e.target.value.trim()||'Rookie';save()});
setInterval(render,1000);render();